# You can copy-paste these sections to snakeconfig.yaml and modify them there
# Any section that is in snakeconfig.yaml will overwrite the one here

umiextract_args: >-
  --umilen 8
  --anchor "ATTGCGCAATG"
  --trailing "GGG"
  --search_region 30
  --fuzzy_umi

star_index_args: >-
  --limitGenomeGenerateRAM 100000000000

star_align_args: >-
  --clip3pAdapterSeq CTGTCTCTTATACACATCT CTGTCTCTTATACACATCT
  --clip3pAdapterMMp 0.1 0.1
  --genomeLoad LoadAndRemove
  --readFilesCommand zcat
  --outSAMtype BAM Unsorted

umicount_args: >-
  --mm_count_primary
  --UMI_correct